<a href="https://colab.research.google.com/github/Jahura7/Mammographic_Mass_Classification_with_a_Decision_Tree/blob/experiment.ipynb/Mammographic_Mass_Classification_with_a_Decision_Tree.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Import Libraries and Set Reproducibility**

In [10]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [11]:
from sklearn.dummy import DummyClassifier
from sklearn.impute import SimpleImputer
from sklearn.metrics import (
    accuracy_score,
    balanced_accuracy_score,
    classification_report,
    ConfusionMatrixDisplay,
    confusion_matrix,
    f1_score,
    precision_score,
    recall_score,
    roc_auc_score,
    RocCurveDisplay,
)

In [4]:
from sklearn.model_selection import (
    train_test_split,
    StratifiedKFold,
    GridSearchCV,
    cross_validate,
)

In [5]:
from sklearn.pipeline import Pipeline
from sklearn.tree import DecisionTreeClassifier, plot_tree

RANDOM_STATE = 42
TEST_SIZE = 0.20

sns.set_theme(style="whitegrid")
pd.set_option("display.max_columns", None)

# **Load and Validate the data**

In [6]:
df = pd.read_csv("mammographic_masses_data_clean.csv")

In [7]:
df.head()

   BI-RADS  Age  Shape  Margin  Density  Target
0        5   67      3       5        3       1
1        5   58      4       5        3       1
2        4   28      1       1        3       0
3        5   57      1       5        3       1
4        5   76      1       4        3       1

In [8]:
df.tail()

     BI-RADS  Age  Shape  Margin  Density  Target
825        4   47      2       1        3       0
826        4   56      4       5        3       1
827        4   64      4       5        3       0
828        5   66      4       5        3       1
829        4   62      3       3        3       0

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 830 entries, 0 to 829
Data columns (total 6 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   BI-RADS  830 non-null    int64
 1   Age      830 non-null    int64
 2   Shape    830 non-null    int64
 3   Margin   830 non-null    int64
 4   Density  830 non-null    int64
 5   Target   830 non-null    int64
dtypes: int64(6)
memory usage: 39.0 KB

In [13]:
df.shape

(830, 6)

In [14]:
df.dtypes

BI-RADS    int64
Age        int64
Shape      int64
Margin     int64
Density    int64
Target     int64
dtype: object

In [15]:
df.isna().sum().to_frame("missing_values")

         missing_values
BI-RADS               0
Age                   0
Shape                 0
Margin                0
Density               0
Target                0

In [16]:
df.duplicated().sum()

np.int64(266)

In [17]:
df.describe().T

         count       mean        std   min   25%   50%   75%   max
BI-RADS  830.0   4.393976   1.888371   0.0   4.0   4.0   5.0  55.0
Age      830.0  55.781928  14.671782  18.0  46.0  57.0  66.0  96.0
Shape    830.0   2.781928   1.242361   1.0   2.0   3.0   4.0   4.0
Margin   830.0   2.813253   1.567175   1.0   1.0   3.0   4.0   5.0
Density  830.0   2.915663   0.350936   1.0   3.0   3.0   3.0   4.0
Target   830.0   0.485542   0.500092   0.0   0.0   0.0   1.0   1.0